version: "1.0"

services:
  db-postgres: 
    image: db-postgres
    volumes:
      - ./db-postgres-data:/var/lib/postgresql/data
    restart: always
    container_name: db
    build:
      context: .
      target: db
    environment:
      - POSTGRES_USER=${DB_POSTGRES_USER}
      - POSTGRES_PASSWORD=${DB_POSTGRES_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - SEED_FILE_NAME=${DB_POSTGRES_SEED}
    ports:
      - ${DB_POSTGRES_PORT}:${DB_POSTGRES_PORT}
  db-pgadmin:
    image: dpage/pgadmin4
    volumes:
      - ./db-pgadmin-data:/var/lib/pgadmin
    restart: always
    container_name: pgadmin
    ports:
      - "${DB_PGADMIN_PORT}:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${DB_PGADMIN_USER}
      PGADMIN_DEFAULT_PASSWORD: ${DB_PGADMIN_PASSWORD}

volumes:
  db-postgres-data:
  db-pgadmin-data:

  